id: P001654
initial_creation_type: ocr
source_metadata:
  id: bdr:W25112
  title: དགུ་རོང་རྒྱལ་སྲས་ཀྱི་རྣམ་ཐར།
  author: ''
  volumes:
    b3345dab036c4d0c88b9e17b3a957983:
      image_group_id: I1GS105472
      title: ''
      volume_number: 1
      total_pages: 174
      base_file: v001.txt
